# ============================================================
#  TaniClaw v1 — PowerShell Installer for Windows
#  Usage:
#    irm https://raw.githubusercontent.com/wansatya/taniclaw/main/install.ps1 | iex
# ============================================================

$ErrorActionPreference = "Stop"

# ── Config ────────────────────────────────────────────────────────────────────
$env:UV_NO_WORKSPACE = "1"
$REPO_URL = "https://github.com/wansatya/taniclaw"
$TANICLAW_VERSION = "1.0.0"
$INSTALL_DIR = if ($env:INSTALL_DIR) { $env:INSTALL_DIR } else { "$HOME\.taniclaw" }

# ── Helpers ───────────────────────────────────────────────────────────────────
function Write-Info($msg) { Write-Host "[TaniClaw] $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "[WARN]     $msg" -ForegroundColor Yellow }
function Write-Header($msg) { Write-Host "`n==> $msg" -ForegroundColor Blue -Style Bold }
function Write-Success($msg) { Write-Host "v $msg" -ForegroundColor Green -Style Bold }

# ── Banner ────────────────────────────────────────────────────────────────────
Write-Host @"

  ████████╗ █████╗ ███╗   ██╗██╗ ██████╗██╗      █████╗ ██╗    ██╗
     ██╔══╝██╔══██╗████╗  ██║██║██╔════╝██║     ██╔══██╗██║    ██║
     ██║   ███████║██╔██╗ ██║██║██║     ██║     ███████║██║ █╗ ██║
     ██║   ██╔══██║██║╚██╗██║██║██║     ██║     ██╔══██║██║███╗██║
     ██║   ██║  ██║██║ ╚████║██║╚██████╗███████╗██║  ██║╚███╔███╔╝
     ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝ ╚═════╝╚══════╝╚═╝  ╚═╝ ╚══╝╚══╝
  v$TANICLAW_VERSION — Lightweight Autonomous Agriculture Skill
  🌱 Food Security Agent for Everyone
"@ -ForegroundColor Green

# ── Check Prerequisites ───────────────────────────────────────────────────────
function Install-Uv {
    if (Get-Command uv -ErrorAction SilentlyContinue) {
        Write-Success "uv found: $(uv --version)"
        return
    }
    Write-Info "Installing uv (fast Python package manager)..."
    powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
    $env:Path += ";$HOME\.cargo\bin"
    if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
        throw "uv installation failed. Please install manually: https://docs.astral.sh/uv/"
    }
}

# ── Get Repo ──────────────────────────────────────────────────────────────────
function Get-Repo {
    Write-Header "Setting up TaniClaw in $INSTALL_DIR..."
    
    if (Test-Path $INSTALL_DIR) {
        Write-Warn "Removing existing directory at $INSTALL_DIR for a fresh installation..."
        Remove-Item -Recurse -Force $INSTALL_DIR
    }

    if (Get-Command git -ErrorAction SilentlyContinue) {
        Write-Info "Cloning from $REPO_URL..."
        git clone --depth=1 $REPO_URL $INSTALL_DIR
    } else {
        Write-Info "git not found - downloading ZIP..."
        $zipUrl = "$REPO_URL/archive/refs/heads/main.zip"
        $zipFile = "$env:TEMP\taniclaw.zip"
        Invoke-WebRequest -Uri $zipUrl -OutFile $zipFile
        Expand-Archive -Path $zipFile -DestinationPath "$env:TEMP\taniclaw_raw" -Force
        Move-Item -Path "$env:TEMP\taniclaw_raw\taniclaw-main\*" -Destination $INSTALL_DIR -Force
        Remove-Item -Recurse -Force "$env:TEMP\taniclaw_raw"
        Remove-Item $zipFile
    }
}

# ── Generate .env ─────────────────────────────────────────────────────────────
function Generate-Env {
    Write-Header "Configuring environment..."
    $envFile = "$INSTALL_DIR\.env"
    $dbPath = "$INSTALL_DIR\taniclaw.db".Replace('\', '/')

    $envContent = @"
# TaniClaw v1 — generated by install.ps1 on $(Get-Date)

TANICLAW_DATABASE_URL=sqlite:///$dbPath
TANICLAW_HOST=127.0.0.1
TANICLAW_PORT=8000
TANICLAW_LOG_LEVEL=INFO
TANICLAW_SCHEDULER_INTERVAL_MINUTES=60
TANICLAW_TIMEZONE=Asia/Jakarta
TANICLAW_WEATHER_API_BASE=https://api.open-meteo.com/v1

# LLM (Groq)
TANICLAW_LLM_ENABLED=$($false -and $env:GROQ_API_KEY).ToString().ToLower()
TANICLAW_GROQ_API_KEY=$($env:GROQ_API_KEY)
TANICLAW_LLM_MODEL=llama-3.1-8b-instant

# Security
TANICLAW_MAX_WATERING_AMOUNT_ML=500
TANICLAW_MAX_DAILY_ACTIONS=50
"@
    $envContent | Out-File -FilePath $envFile -Encoding utf8
    Write-Success ".env generated (using SQLite)"
}

# ── Main ──────────────────────────────────────────────────────────────────────
try {
    Install-Uv
    Get-Repo
    Generate-Env

    Write-Header "Installing TaniClaw via uv..."
    Set-Location $INSTALL_DIR
    uv venv .venv --python 3.13
    uv pip install -e .

    Write-Success "TaniClaw installed!"
    Write-Info "`nTo start TaniClaw, run:"
    Write-Host "cd $INSTALL_DIR; uv run taniclaw start" -ForegroundColor Cyan
} catch {
    Write-Error $_
    exit 1
}
